### PR TITLE
Fix headers bugs

### LINKED ISSUE #265: Axel doesn't include the User-Agent header in http requests
There is a bug since 7525c57ee7dafc36cd2f33e670f53a231a7b14ea that makes Axel not send the User-Agent header (neither the default nor a custom one). With the only exception being the user setting one or more custom headers (-H) to be included and afterwards setting a custom User-Agent string - in which case the very first custom header will get omitted instead:

> ./axel -U CustomUA -H "Example: Header1"  www.test
>
> GET http://www.test/
> Host: www.test
> Accept: */*
> Range: bytes=0-
> Example: Header1

> ./axel -H "Example: Header1" -H "Another: Header2" -U CustomUA  www.test
>
> GET http://www.test/
> Host: www.test
> Accept: */*
> Range: bytes=0-
> User-Agent: CustomUA
> Another: Header2

Opening a PR soon.

### LINKED ISSUE #266: Axel parses more custom headers than it was designed to resulting in mememory corruption
There is a #224 hard limit of additional/custom headers an user can include with Axel's HTTP request. At the moment it's 9 (+1 for User-Agent). However Axel does not check how many custom headers have been appended which may result in memory corruption. Sometimes it will still go through with the request, but sometimes it  SEGFAULTs or worse, leaks out parts of memory to the remote host. 

> ./axel -H "A: a" -H "B: b" -H "C: c" -H "D: d" -H "E: e" -H "F: f" -H "G: g" -H "H: h" -H "I: i" -H "J: j" -H "K: k" -H "L: l" -H "M: m" -H "N: n" -H "O: o" -H "P: p" -H "Q: q" -H "R: r" -H "S: s"  www.test
> Segmentation fault (core dumped)

> ./axel -H "A: aaaaaaaaaaaaaaaaaaaaaaaaa" -H "B: b" -H "C: c" -H "D: d" -H "E: e" -H "F: f" -H "G: g" -H "HHHHHHHHHHHHHHHHHHHHHHH: h" -H "I: i" -H "J: j" -H "K: k" -H "L: l" -H "M: m" -H "N: n" -H "O: o" -H "P: p" -H "Q: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"   www.test
> Initializing download: qqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqq
>
> GET http://qqqqqqqqqqqqqqqqqqQ/
> Host: qqqqqqqqqqqqqqqqqqQ
> Accept: */*
> Range: bytes=0-
> A: aaaaaaaaaaaaaaaaaaaaaaaaa
> B: b
> C: c
> D: d
> E: e
> F: f
> G: g
> HHHHHHHHHHHHHHHHHHHHHHH: h
> I: i
> J: j
> K: k
> L: l
> M: m
> N: n
> O: o
> P: p
> Q: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ: qqqqqqqqqqqqqqqqqqqqqqqqq

I've made a PR that includes a simple check to fix this. It could be good to increase the MAX_ADD_HEADERS before somebody implements dynamic memory allocation for headers.

### PR DESCRIPTION
**Pull request by vewupom**
Small changes to make sure User-Agent and custom headers all get included in the request. Also a safety check to make sure Axel doesn't write more custom headers to memory than it has space for.

I got rid of the cur_head variable because it didn't seem to be doing anything except for introducing a bug.

fixes #265, fixes #266

### CODE REVIEW

**Comment by ismaell** [comment]
Please fix your Git configuration and submit again, the commits must have a valid configuration and email.

Additionally, please keep your lines under 80 characters.

The rest looks good.

File: src/text.c [hunk 1]
```diff
@@ -131,7 +131,12 @@ main(int argc, char *argv[])
 				      "User-Agent", optarg);
 			break;
 		case 'H':
-			strlcpy(conf->add_header[cur_head++], optarg,
+			if(!(conf->add_header_count<MAX_ADD_HEADERS)) {
```
Comment (ismaell) [inline src/text.c]: this could be:
``` C
if (conf->addr_header_count >= MAX_ADD_HEADERS) {
```

**Comment by ismaell** [comment]
Hello?

**Comment by ismaell** [comment]
I'll make an exception with this one :/
